apiVersion: v1
kind: Pod
metadata:
  name: shell
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: ssh-key-secret
      defaultMode: 0600
  containers:
  - name: shell
    image: gcr.io/thesecretaryofwar/python:v1
    imagePullPolicy: Always
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: /etc/secret-volume
    command: ["sleep", "infinity"]
  restartPolicy: Never
