apiVersion: v1
kind: Pod
metadata:
  name: wikidiff-{{ id1 }}-{{ id2 }}
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: ssh-key-secret
      defaultMode: 0600
  containers:
  - name: wikidiff
    image: gcr.io/thesecretaryofwar/python:v1
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 1
        memory: "8Gi"
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: /etc/secret-volume
    command: ["bash", "wikidiff.sh", "{{ id1 }}", "{{ id2 }}"]
  restartPolicy: OnFailure
